[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fitz>=0.0.1.dev2",
    "replit-object-storage>=1.0.2",
    "translators>=6.0.1",
]
